### ISSUE TITLE
Sink Connector for Kinesis

### ISSUE THREAD

**Issue by abhibhatia98** [lf-edge/ekuiper#3040]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

Hi, 

I am working on creating a Sink connector for AWS Kinesis Stream. Below are the steps that I have followed till now by following [this ](https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#compilation)->

1. Clone the ekuiper repository [this ](https://github.com/lf-edge/ekuiper). 
2. Install go version 1.22, try to build it and ran it using  `make, cd _build/kuiper-x.x.x-linux-amd64/, bin/kuiperd` commands and it is working fine. I have tested it using management UI.
3. In extensions -> Sinks -> Created a new directory with name kinesis having following files 
```
kinesis/
│   ├── kinesis.go
│   ├── kinesis.json
│   └── ext/
│         └── kinesis.go
│         └── kinesis_test.go 
```
After that I run below commands
```
export build=test
go build -trimpath -o ./_build/$build/bin/kuiperd cmd/kuiperd/main.go
go build -trimpath --buildmode=plugin -o ./_build/$build/plugins/sinks/kinesis@v1.0.0.so extensions/sinks/kinesis/kinesis.go
```

Now for deployment I am trying to utilize management UI, docs says we have to create a zip file with .so file from `ekuiper/_build/test/plugins/sinks/ ` and a yaml file (which I am not very clear, what I have to put in it ?) So I just added json file that I have above, and tried to upload it, gives me below error
```
{
    "error": 1000,
    "message": "sinks plugins create command error: fail to install plugin: invalid zip file: expectFiles: 1, got filenames:[], zipFiles: [kinesis/kinesis.json kinesis/kinesis@v1.0.0.so], yamlFileChecked:false, soFileChecked:false"
}
```

Request you to please help on this.

If required I can share the file content as well.

Thanks 
Abhishek

**Comment by ngjaying** [comment]
@abhibhatia98 In you zip file, you have a folder kinesis in the top level. The so file and json file must be in the top level of the zip file. Move them out of the kinesis folder to the root of the zip file.

**Comment by abhibhatia98** [comment]
Now gets another error:


`{"error":1000,"message":"sinks plugins create command error: fail to install plugin: cannot open /kuiper/plugins/sinks/kinesis@v1.0.0.so: plugin.Open("/kuiper/plugins/sinks/kinesis@v1.0.0.so"): Error loading shared library libresolv.so.2: No such file or directory (needed by /kuiper/plugins/sinks/kinesis@v1.0.0.so)"}`

**Comment by ngjaying** [comment]
This problem is documented in the https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#deployment.  Try to use ekuiper slim docker image instead of default(alpine) image

**Comment by abhibhatia98** [comment]
I have ekuiper running using below command in ubuntu machine using repository master branch

`make, cd _build/kuiper-x.x.x-linux-amd64/, bin/kuiperd`  I was trying on this previously.  

Also I have another instance of ekuiper running in docker container using image `emqx/ekuiper-manager:latest`

So I tried using this by below commands 

```
docker exec -it a01bf1533302 /bin/sh
# apk add gcompat
/bin/sh: 1: apk: not found
```

Please confirm do I have to change image ??

Thanks

**Comment by ngjaying** [comment]
Did you follow the tutorial. What steps have you done until now? Are you able to run https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#debug-and-run-the-plugin?

**Comment by abhibhatia98** [comment]
Docs are really confusing to understand, I havn't followed this exactly, but do the same for Kinesis  -> 

If I try to follow the above article and ran below commands, 

 ```
  go build -trimpath -o ./_build/$build/bin/kuiperd cmd/kuiperd/main.go
  go build -trimpath --buildmode=plugin -o ./_build/$build/plugins/sinks/Mysql@v1.0.0.so extensions/sinks/mysql/mysql.go
```
Error I got is :-
```
extensions/sinks/mysql/mysql.go:54:20: ctx.TransformOutput undefined (type api.StreamContext has no field or method TransformOutput)
extensions/sinks/mysql/mysql.go:84:10: cannot use &mysqlSink{} (value of type *mysqlSink) as api.Sink value in return statement: *mysqlSink does not implement api.Sink (missing method Connect)
```

the kinesis plugin that I compiled inside the repo code, can't I use that within same ekuiper instance which is running by bin/kuiperd command ?

**Comment by ngjaying** [comment]
Please use master-1.14 branch. Master branch is the development branch for v2 alpha, there are some API changes and the doc had not updated.

**Comment by abhibhatia98** [comment]
Hi @ngjaying, I am already on master-1.14.

**Comment by abhibhatia98** [comment]
> This problem is documented in the https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#deployment. Try to use ekuiper slim docker image instead of default(alpine) image

Hi @ngjaying, thanks it works on lfedge/ekuiper:1.14-slim-python docker image,  

I see CPU utilization for Alpine is almost half of this debian based, So is there any way I can use this connector in Alpine image ?


Thanks 
Abhishek

**Comment by ngjaying** [comment]
Check https://ekuiper.org/docs/en/latest/extension/native/develop/plugins_tutorial.html#deployment for the last paragraph.
